baseURL: "https://georein.com/"
languageCode: en-us
title: Reinhardt Botha
theme: PaperModX

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

minify:
  disableXML: true
  # minifyOutput: true

languages:
  en:
    languageName: "English"
    weight: 1    
    menu:
      main:
#        - name: Home
#          url: //
#          weight: 1
        - name: Posts
          url: /posts/
          weight: 2
        - name: Tags
          url: /tags/
          weight: 4
        - name: Search
          url: /search/
          weight: 5
        - name: About
          url: /about/
          weight: 7
        - name: Contact
          url: /contact/
          weight: 10

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  description: "georein.com - a personal blog-style website by Reinhardt Botha."
  author:
    - Reinhardt Botha
  ShowShareButtons: true
  

  mainSections:
    - posts
  #disableAnchoredHeadings: true
  images: ["cover.png"]
  DateFormat: "2006-01-02"
  useCustomAnalytics: false

  defaultTheme: auto
  # disableThemeToggle: true

  ShareButtons: ["linkedin", "twitter", "reddit", "facebook", "whatsapp", "telegram"]
  ShowReadingTime: true
  ShowWordCount: true
  # disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowToc: true
  TocOpen: true
  TocSide: "left"
  EnableInstantClick: true
  EnableImageZoom: true


  homeInfoParams:
    #Title: ""
    Content: |
      ***Welcome to georein.com - a personal blog by Reinhardt Botha for all things GIS.***
  

      To get started, please head to the [<u>Posts</u>](posts) page to check out what I have to share. 
      You can also go to the [<u>About</u>](about) page to learn more about me and the website. Or if you wish to contact me, you can find all my details on the [<u>Contact</u>](contact) page.
   
      Enjoy!
      
  socialIcons:
    - name: linkedin-simple
      url: "https://www.linkedin.com/in/wrbotha"
    - name: youtube-simple
      url: "https://www.youtube.com/channel/UCqMntUFI_ktxiA3KDmFvItQ"
    - name: rss-simple
      url: "index.xml"



  # label:
  #     text: "Home"
  #     icon: icon.png
  #     iconHeight: 35

  # assets:
  #     favicon: "<link / abs url>"
  #     favicon16x16: "<link / abs url>"
  #     favicon32x32: "<link / abs url>"
  #     apple_touch_icon: "<link / abs url>"
  #     safari_pinned_tab: "<link / abs url>"

  # cover:
  #     hidden: true # hide everywhere but not in structured data
  #     hiddenInList: true # hide on list pages and home
  #     hiddenInSingle: true # hide on single page

  # fuseOpts:
  #     isCaseSensitive: false
  #     shouldSort: true
  #     location: 0
  #     distance: 1000
  #     threshold: 0.4
  #     minMatchCharLength: 0
  #     keys: ["title", "permalink", "summary", "content"]


taxonomies:
  category: categories
  tag: tags
  series: series

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: dracula
    lineNos: false
    noClasses: false

privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true